"""empty message

Revision ID: 686a373b3c74
Revises: 19d3b28244f7
Create Date: 2022-04-02 15:31:22.046114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686a373b3c74'
down_revision = '19d3b28244f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_event', sa.Column('player_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'match_event', 'player', ['player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_event', type_='foreignkey')
    op.drop_column('match_event', 'player_id')
    # ### end Alembic commands ###
